name: Build and release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev libacl1-dev liblzma-dev libbz2-dev
      - run: make zipper
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.11.2
        if: contains(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: zipper
          tag: ${{ github.ref }}
          overwrite: true
