name: Build and release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: make zipper
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}