name: Build and release
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libarchive-dev libacl1-dev liblzma-dev libbz2-dev
      - run: make zipper
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}