name: Windows release
on:
  push:
    tags:
      - v*
jobs:
  win64:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - run: make zipper.exe
