name: Windows release
on:
  push:
    tags:
      - v*
jobs:
  win64:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc make
    - run: make zipper.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.2.1
      if: contains(github.ref, 'refs/tags/v')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: zipper.exe
        tag: ${{ github.ref }}
        overwrite: true
